<Project>
    <!-- Make F# support Central Package Management -->
    <PropertyGroup>
        <DisableImplicitSystemValueTupleReference>true</DisableImplicitSystemValueTupleReference>
        <DisableImplicitFSharpCoreReference>true</DisableImplicitFSharpCoreReference>
    </PropertyGroup>
    <PropertyGroup Condition="'$(GITHUB_ACTIONS)' == 'true'">
        <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    </PropertyGroup>
    <PropertyGroup>
        <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
        <RestoreLockedMode Condition="'$(ContinuousIntegrationBuild)' == 'true'">true</RestoreLockedMode>
    </PropertyGroup>
    <PropertyGroup>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <Authors>Maxime Mangel</Authors>
        <PackageProjectUrl>https://github.com/glutinum-org/hub</PackageProjectUrl>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
    </PropertyGroup>
    <ItemGroup Condition="'$(PackageId)'!='Glutinum.Hub.Build'">
        <PackageReference Include="FSharp.Core" />
    </ItemGroup>
</Project>
