<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="EasyBuild.PackageReleaseNotes.Tasks" Version="2.1.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageVersion>
    <PackageVersion Include="Fable.Core" Version="5.2.0" />
    <PackageVersion Include="Fable.Package.SDK" Version="1.4.1">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageVersion>
    <PackageVersion Include="Fable.Promise" Version="3.2.0" />
    <PackageVersion Include="FSharp.Core" Version="10.1.301" />
    <PackageVersion Include="Glutinum.Node" Version="1.0.0-beta.3" />
    <PackageVersion Include="Glutinum.Types" Version="1.0.0-beta.4" />
    <PackageVersion Include="Glutinum.Web" Version="1.0.0-beta.3" />
    <PackageVersion Include="Scriptorium.Nib" Version="0.4.1" />
    <PackageVersion Include="Scriptorium.Nib.Browser" Version="0.3.1" />
    <PackageVersion Include="Scriptorium.Quill" Version="0.7.1" />
  </ItemGroup>
</Project>
